################################
# Site Settings
################################
title         : Michael Ravedoni
description   : "Michael Ravedoni' website"
contact_email : michael.ravedoni@gmail.com
logo          : profile-mr.png
author        : Michael Ravedoni

baseurl       : "" # the subpath of your site, e.g. /blog
site_url      : "http://localhost:4000" # the base hostname & protocol for your site
url           : "http://localhost:4000"
environment   : development

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE', 'travis.yml', 'node_modules', 'package-lock.json', 'package.json', 'deploy.js', 'deploy-model.js']

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Langage

languages: ['fr', 'de', 'en', 'it']
#languages: ['fr']
exclude_from_localizations: ["images", "js", "css", "favicon", "doc", "robots.txt", "card.rdf"]
defaultLang: fr

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /publications/:path/
  tb:
    output: true
    permalink: /publications/2018-tb-bibliotheque-plateforme/:path/

################################
# Jekyll Plugins
################################
plugins:
  - jekyll-assets

gems:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jekyll-email-protect

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
