# Site settings
title: "Michael Ravedoni"
description: "A resume of Michael Ravedoni"
contact_email: michael.ravedoni@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
site_url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://localhost:4000"
environment: development

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE', 'travis.yml', 'node_modules', 'package-lock.json', 'package.json', 'deploy.js']

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Michael Ravedoni"
resume_title:                   ""
resume_contact_email:           "michael.ravedoni@gmail.com"
# resume_contact_telephone:       ""
resume_contact_address:         "Sion-Lausanne-Fribourg"
# resume_contact_site:         ""
# resume_header_contact_info: "michael.ravedoni@gmail.com"
resume_header_intro: ""

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
resume_section_languages:       true
resume_section_testimonials:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/michaelravedoni"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/michael-ravedoni/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://michael.ravedoni.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   developer

# Langage

languages: ['fr', 'de', 'en']
exclude_from_localizations: ["images", "js", "css", "favicon"]
defaultLang: fr

# Plugins
plugins:
  - jekyll-assets

gems:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
