################################
# Site Settings
################################
title         : Michael Ravedoni
description   : "Michael Ravedoni' website"
contact_email : michael@ravedoni.com
logo          : profile-mr.png
author        : Michael Ravedoni

baseurl       : "" # the subpath of your site, e.g. /blog
site_url      : "http://localhost:4000" # the base hostname & protocol for your site
url           : "http://localhost:4000"
environment   : development

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'LICENSE', 'travis.yml', 'node_modules', 'package-lock.json', 'package.json', 'deploy.js', 'deploy-model.js', 'env.json', 'env-model.json', 'brunch']

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
#source: app/src
#destination: app/www

# Langage

languages: ['fr', 'de', 'en', 'it']
#languages: ['fr']
exclude_from_localizations: ["images", "js", "css", "favicon", "doc", "robots.txt", "card.rdf"]
defaultLang: fr

collections:
  articles:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /publications/:path/
  tb:
    output: true
    permalink: /publications/2018-tb-bibliotheque-plateforme/:path/

# PWA
pwa:
  sw_src_filepath: service-worker.js # Optional
  dest_js_directory: /js # Required
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js

################################
# Jekyll Plugins
################################
plugins:
  - jekyll-assets

gems:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jekyll-email-protect
  - jekyll-pwa-plugin

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
